import bcrypt from 'bcryptjs';

const day = (offset = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toISOString().split('T')[0];
};

const hash = (pw) => bcrypt.hashSync(pw, 10);

export function seedData() {
  return {
    users: [
      {
        id: 1,
        fullName: 'Sarah Chen',
        email: 'sarah@mconnect.com',
        passwordHash: hash('password123'),
        isAdmin: false,
        avatarUrl: 'https://i.pravatar.cc/150?img=1',
        bio: 'Senior Software Engineer with 10+ years of experience in full-stack development. Passionate about mentoring the next generation of developers.',
        expertiseTags: ['JavaScript', 'React', 'Node.js', 'System Design'],
        rating: 4.8,
        isMentorProfileComplete: true,
        createdAt: '2025-01-15T10:00:00Z',
      },
      {
        id: 2,
        fullName: 'James Wilson',
        email: 'james@mconnect.com',
        passwordHash: hash('password123'),
        isAdmin: false,
        avatarUrl: 'https://i.pravatar.cc/150?img=3',
        bio: 'Product Manager at a Fortune 500 company. I help aspiring PMs navigate their career journey.',
        expertiseTags: ['Product Management', 'Strategy', 'Leadership', 'Agile'],
        rating: 4.6,
        isMentorProfileComplete: true,
        createdAt: '2025-02-10T09:00:00Z',
      },
      {
        id: 3,
        fullName: 'Priya Patel',
        email: 'priya@mconnect.com',
        passwordHash: hash('password123'),
        isAdmin: false,
        avatarUrl: 'https://i.pravatar.cc/150?img=5',
        bio: '',
        expertiseTags: [],
        rating: 0,
        isMentorProfileComplete: false,
        createdAt: '2025-06-01T14:00:00Z',
      },
      {
        id: 4,
        fullName: 'Alex Kim',
        email: 'alex@mconnect.com',
        passwordHash: hash('password123'),
        isAdmin: false,
        avatarUrl: 'https://i.pravatar.cc/150?img=8',
        bio: '',
        expertiseTags: [],
        rating: 0,
        isMentorProfileComplete: false,
        createdAt: '2025-07-10T08:00:00Z',
      },
      {
        id: 5,
        fullName: 'Dr. Maria Garcia',
        email: 'maria@mconnect.com',
        passwordHash: hash('password123'),
        isAdmin: false,
        avatarUrl: 'https://i.pravatar.cc/150?img=9',
        bio: 'Data Science Lead with expertise in ML, AI, and analytics. Published researcher and conference speaker.',
        expertiseTags: ['Machine Learning', 'Python', 'Data Science', 'AI'],
        rating: 4.9,
        isMentorProfileComplete: true,
        createdAt: '2024-11-20T11:00:00Z',
      },
      {
        id: 6,
        fullName: 'Admin User',
        email: 'admin@mconnect.com',
        passwordHash: hash('admin123'),
        isAdmin: true,
        avatarUrl: 'https://i.pravatar.cc/150?img=12',
        bio: 'Platform administrator.',
        expertiseTags: [],
        rating: 0,
        isMentorProfileComplete: false,
        createdAt: '2024-01-01T00:00:00Z',
      },
    ],
    posts: [
      {
        id: 1,
        authorId: 1,
        content: 'Just wrapped up an amazing mentoring session on React performance optimization. Remember: useMemo and useCallback are powerful, but only use them when you have a real performance problem to solve! Premature optimization is the root of all evil.',
        mediaUrl: null,
        mediaType: null,
        reactions: { like: 12, celebrate: 5, support: 3 },
        userReactions: {},
        commentCount: 4,
        createdAt: '2026-07-20T10:30:00Z',
      },
      {
        id: 2,
        authorId: 2,
        content: 'Excited to announce that I will be hosting a free webinar on "Breaking into Product Management" next week! We will cover the essential skills, common career paths, and how to build your PM portfolio. Stay tuned for the link!',
        mediaUrl: null,
        mediaType: null,
        reactions: { like: 24, celebrate: 15, support: 8 },
        userReactions: {},
        commentCount: 7,
        createdAt: '2026-07-19T14:00:00Z',
      },
      {
        id: 3,
        authorId: 5,
        content: 'New blog post: "5 Python Libraries Every Data Scientist Should Know in 2026." From Polars to Lightning, the ML ecosystem keeps evolving. Check it out and let me know your favorites!',
        mediaUrl: 'https://picsum.photos/800/400',
        mediaType: 'image',
        reactions: { like: 31, celebrate: 10, support: 6 },
        userReactions: {},
        commentCount: 9,
        createdAt: '2026-07-18T09:15:00Z',
      },
      {
        id: 4,
        authorId: 3,
        content: 'First week of mentorship with Sarah is done and I have already learned so much about component composition patterns. Feeling grateful for this platform and the opportunity to learn from experienced engineers!',
        mediaUrl: null,
        mediaType: null,
        reactions: { like: 18, celebrate: 22, support: 11 },
        userReactions: {},
        commentCount: 5,
        createdAt: '2026-07-17T16:45:00Z',
      },
      {
        id: 5,
        authorId: 4,
        content: 'Anyone else transitioning from traditional software engineering to data science? Would love to connect and share resources. Currently working through Andrew Ng\'s ML course.',
        mediaUrl: null,
        mediaType: null,
        reactions: { like: 8, celebrate: 3, support: 14 },
        userReactions: {},
        commentCount: 6,
        createdAt: '2026-07-16T11:20:00Z',
      },
    ],
    comments: [
      { id: 1, postId: 1, authorId: 3, text: 'This is so helpful! I always struggle with knowing when to use useMemo. Thanks for the practical advice.', parentId: null, createdAt: '2026-07-20T11:00:00Z' },
      { id: 2, postId: 1, authorId: 4, text: 'Great point about profiling first. Do you have any recommended tools for React performance profiling?', parentId: null, createdAt: '2026-07-20T11:30:00Z' },
      { id: 3, postId: 1, authorId: 1, text: 'React DevTools Profiler is the best starting point. Also look into Lighthouse for overall performance metrics.', parentId: 2, createdAt: '2026-07-20T12:00:00Z' },
      { id: 4, postId: 1, authorId: 2, text: 'Even as a PM, I find this useful to understand what my engineering team deals with. Thanks for sharing!', parentId: null, createdAt: '2026-07-20T13:00:00Z' },
      { id: 5, postId: 2, authorId: 3, text: 'Cannot wait for this webinar! I have been thinking about transitioning to PM.', parentId: null, createdAt: '2026-07-19T15:00:00Z' },
      { id: 6, postId: 2, authorId: 4, text: 'Will there be a recording available afterwards? I might not be able to attend live.', parentId: null, createdAt: '2026-07-19T15:30:00Z' },
      { id: 7, postId: 2, authorId: 2, text: 'Yes! I will share the recording with everyone who registers.', parentId: 6, createdAt: '2026-07-19T16:00:00Z' },
      { id: 8, postId: 3, authorId: 1, text: 'Polars has been a game-changer for my data pipelines. Much faster than Pandas for large datasets.', parentId: null, createdAt: '2026-07-18T10:00:00Z' },
      { id: 9, postId: 3, authorId: 4, text: 'Adding this to my reading list! I have been meaning to explore Lightning for model training.', parentId: null, createdAt: '2026-07-18T11:00:00Z' },
      { id: 10, postId: 4, authorId: 1, text: 'You are doing great, Priya! Your progress has been impressive.', parentId: null, createdAt: '2026-07-17T17:00:00Z' },
      { id: 11, postId: 4, authorId: 2, text: 'This is what mentorship is all about. Love seeing these success stories!', parentId: null, createdAt: '2026-07-17T18:00:00Z' },
      { id: 12, postId: 5, authorId: 5, text: 'Welcome to the field, Alex! Happy to share some resources. The transition is challenging but rewarding.', parentId: null, createdAt: '2026-07-16T12:00:00Z' },
      { id: 13, postId: 5, authorId: 1, text: 'I made a similar transition years ago. Feel free to reach out if you need any advice!', parentId: null, createdAt: '2026-07-16T13:00:00Z' },
    ],
    conversations: [
      {
        id: 1,
        type: 'direct',
        participants: [{ userId: 1 }, { userId: 3 }],
        lastMessage: 'See you at our session tomorrow at 2pm!',
        lastMessageAt: '2026-07-21T18:00:00Z',
        createdAt: '2026-07-01T10:00:00Z',
      },
      {
        id: 2,
        type: 'direct',
        participants: [{ userId: 1 }, { userId: 4 }],
        lastMessage: 'I have shared the resources we discussed. Let me know if you have any questions.',
        lastMessageAt: '2026-07-21T15:30:00Z',
        createdAt: '2026-07-02T10:00:00Z',
      },
      {
        id: 3,
        type: 'direct',
        participants: [{ userId: 2 }, { userId: 3 }],
        lastMessage: 'Looking forward to the webinar next week!',
        lastMessageAt: '2026-07-21T12:00:00Z',
        createdAt: '2026-07-03T10:00:00Z',
      },
      {
        id: 4,
        type: 'group',
        participants: [{ userId: 1 }, { userId: 2 }, { userId: 3 }, { userId: 4 }, { userId: 5 }],
        lastMessage: 'Maria: Great discussion everyone! Let us continue next week.',
        lastMessageAt: '2026-07-20T17:00:00Z',
        groupName: 'Mentorship Circle',
        groupIconUrl: 'https://i.pravatar.cc/150?img=60',
        createdAt: '2026-07-01T10:00:00Z',
      },
      {
        id: 5,
        type: 'direct',
        participants: [{ userId: 5 }, { userId: 4 }],
        lastMessage: 'Your ML project proposal looks promising. Let us refine the scope.',
        lastMessageAt: '2026-07-19T14:00:00Z',
        createdAt: '2026-07-04T10:00:00Z',
      },
    ],
    messages: [
      { id: 1, conversationId: 1, senderId: 3, text: 'Hi Sarah! Quick question about the useEffect cleanup function we discussed.', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T16:00:00Z', readAt: '2026-07-21T16:01:00Z' },
      { id: 2, conversationId: 1, senderId: 1, text: 'Of course! What specifically are you confused about?', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T16:05:00Z', readAt: '2026-07-21T16:06:00Z' },
      { id: 3, conversationId: 1, senderId: 3, text: 'When should I return a cleanup function vs just letting the component unmount naturally?', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T16:10:00Z', readAt: '2026-07-21T16:11:00Z' },
      { id: 4, conversationId: 1, senderId: 1, text: 'Great question! You need cleanup when your effect creates something that persists outside the component lifecycle - like timers, subscriptions, or event listeners. If it is just a one-time API call, you usually do not need cleanup.', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T16:15:00Z', readAt: '2026-07-21T16:20:00Z' },
      { id: 5, conversationId: 1, senderId: 3, text: 'That makes so much more sense now. Thank you!', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T16:20:00Z', readAt: '2026-07-21T16:21:00Z' },
      { id: 6, conversationId: 1, senderId: 1, text: 'See you at our session tomorrow at 2pm!', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T18:00:00Z', readAt: null },
      { id: 7, conversationId: 2, senderId: 1, text: 'Here are the resources I mentioned: React docs on custom hooks, a great article on component composition, and my favorite talk on advanced patterns.', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T15:25:00Z', readAt: '2026-07-21T15:29:00Z' },
      { id: 8, conversationId: 2, senderId: 1, text: 'I have shared the resources we discussed. Let me know if you have any questions.', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T15:30:00Z', readAt: null },
      { id: 9, conversationId: 3, senderId: 2, text: 'Hi Priya! Just wanted to confirm you are registered for the webinar.', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T11:30:00Z', readAt: '2026-07-21T11:45:00Z' },
      { id: 10, conversationId: 3, senderId: 3, text: 'Yes, I registered yesterday! Looking forward to it.', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T11:45:00Z', readAt: '2026-07-21T11:46:00Z' },
      { id: 11, conversationId: 3, senderId: 2, text: 'Looking forward to the webinar next week!', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-21T12:00:00Z', readAt: null },
      { id: 12, conversationId: 5, senderId: 4, text: 'Dr. Garcia, here is my project proposal for the ML classification model.', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-19T13:00:00Z', readAt: '2026-07-19T13:30:00Z' },
      { id: 13, conversationId: 5, senderId: 5, text: 'Your ML project proposal looks promising. Let us refine the scope.', attachmentUrl: null, messageType: 'text', sentAt: '2026-07-19T14:00:00Z', readAt: null },
    ],
    mentorshipRequests: [
      { id: 1, mentorId: 1, menteeId: 3, message: 'Hi Sarah, I admire your work in React and would love to learn from your experience. Could you mentor me for 3 months?', duration: '3 months', status: 'pending', createdAt: '2026-07-18T09:00:00Z' },
      { id: 2, mentorId: 1, menteeId: 4, message: 'Hello! I am transitioning into frontend development and would really appreciate your guidance.', duration: '1 month', status: 'accepted', createdAt: '2026-07-10T14:30:00Z' },
      { id: 3, mentorId: 2, menteeId: 3, message: 'I am interested in moving into product management. Would you be open to mentoring me?', duration: '6 months', status: 'pending', createdAt: '2026-07-20T11:00:00Z' },
      { id: 4, mentorId: 5, menteeId: 4, message: 'Dr. Garcia, I am passionate about data science and would love your mentorship in building ML skills.', duration: '3 months', status: 'pending', createdAt: '2026-07-21T08:15:00Z' },
    ],
    sessions: [
      { id: 1, mentorId: 1, menteeId: 3, title: 'React Hooks Deep Dive', date: day(0), time: '14:00', status: 'upcoming', videoCallUrl: 'https://meet.google.com/placeholder-abc' },
      { id: 2, mentorId: 1, menteeId: 4, title: 'Career Transition Planning', date: day(0), time: '16:00', status: 'upcoming', videoCallUrl: 'https://meet.google.com/placeholder-def' },
      { id: 3, mentorId: 2, menteeId: 3, title: 'Intro to Product Thinking', date: day(3), time: '10:00', status: 'upcoming', videoCallUrl: 'https://meet.google.com/placeholder-ghi' },
      { id: 4, mentorId: 5, menteeId: 4, title: 'ML Fundamentals Review', date: day(-15), time: '11:00', status: 'completed', videoCallUrl: 'https://meet.google.com/placeholder-jkl' },
      { id: 5, mentorId: 1, menteeId: 3, title: 'State Management Patterns', date: day(-10), time: '14:00', status: 'completed', videoCallUrl: 'https://meet.google.com/placeholder-mno' },
    ],
    availability: [
      {
        mentorId: 1,
        slots: [
          { day: 'Monday', startTime: '09:00', endTime: '12:00', recurring: true },
          { day: 'Monday', startTime: '14:00', endTime: '17:00', recurring: true },
          { day: 'Wednesday', startTime: '10:00', endTime: '13:00', recurring: true },
          { day: 'Friday', startTime: '09:00', endTime: '11:00', recurring: true },
        ],
      },
      {
        mentorId: 2,
        slots: [
          { day: 'Tuesday', startTime: '13:00', endTime: '16:00', recurring: true },
          { day: 'Thursday', startTime: '10:00', endTime: '12:00', recurring: true },
        ],
      },
      {
        mentorId: 5,
        slots: [
          { day: 'Monday', startTime: '15:00', endTime: '18:00', recurring: true },
          { day: 'Thursday', startTime: '14:00', endTime: '17:00', recurring: true },
        ],
      },
    ],
    notifications: [
      { id: 1, userId: 1, type: 'mentorship_request', message: 'Priya Patel sent you a mentorship request for 3 months.', read: false, linkTo: '/dashboard', createdAt: '2026-07-18T09:00:00Z' },
      { id: 2, userId: 1, type: 'session_reminder', message: 'You have a session with Priya Patel today at 2:00 PM - React Hooks Deep Dive.', read: false, linkTo: '/dashboard', createdAt: '2026-07-22T08:00:00Z' },
      { id: 3, userId: 3, type: 'new_comment', message: 'Sarah Chen commented on your post: "You are doing great, Priya!"', read: true, linkTo: '/feed', createdAt: '2026-07-17T17:00:00Z' },
      { id: 4, userId: 3, type: 'session_reminder', message: 'Upcoming session with Sarah Chen tomorrow at 2:00 PM.', read: true, linkTo: '/dashboard', createdAt: '2026-07-21T08:00:00Z' },
      { id: 5, userId: 4, type: 'new_comment', message: 'Dr. Maria Garcia commented on your post: "Welcome to the field, Alex!"', read: false, linkTo: '/feed', createdAt: '2026-07-16T12:00:00Z' },
      { id: 6, userId: 4, type: 'mentorship_request', message: 'Your mentorship request to Dr. Maria Garcia is pending.', read: true, linkTo: '/dashboard', createdAt: '2026-07-21T08:15:00Z' },
      { id: 7, userId: 2, type: 'mentorship_request', message: 'Priya Patel sent you a mentorship request for 6 months.', read: false, linkTo: '/dashboard', createdAt: '2026-07-20T11:00:00Z' },
      { id: 8, userId: 1, type: 'new_comment', message: 'James Wilson commented on your post about React performance.', read: true, linkTo: '/feed', createdAt: '2026-07-20T13:00:00Z' },
    ],
    reviews: [
      { id: 1, mentorId: 1, menteeId: 3, rating: 5, text: 'Sarah is an incredible mentor. She breaks down complex React concepts into simple, actionable steps.', createdAt: '2026-07-01T10:00:00Z' },
      { id: 2, mentorId: 1, menteeId: 4, rating: 4, text: 'Very structured sessions with clear takeaways. Highly recommend for career transitions.', createdAt: '2026-07-02T10:00:00Z' },
      { id: 3, mentorId: 2, menteeId: 3, rating: 5, text: 'James gave me a great roadmap for breaking into product management.', createdAt: '2026-07-03T10:00:00Z' },
      { id: 4, mentorId: 5, menteeId: 4, rating: 5, text: 'Dr. Garcia is brilliant and very patient. My ML skills improved enormously.', createdAt: '2026-07-04T10:00:00Z' },
    ],
    stories: [
      {
        id: 1,
        userId: 1,
        mediaUrl: null,
        mediaType: null,
        text: 'Excited to kick off a new cohort of mentees this week. Let us build great things together!',
        caption: '',
        comments: [
          { id: 1, storyId: 1, authorId: 3, text: 'Congratulations Sarah! Looking forward to our sessions.', createdAt: '2026-07-21T09:00:00Z' },
        ],
        createdAt: '2026-07-21T08:00:00Z',
        expiresAt: '2026-08-05T08:00:00Z',
      },
      {
        id: 2,
        userId: 5,
        mediaUrl: null,
        mediaType: null,
        text: 'Sharing my favorite paper on attention mechanisms today. Deep learning keeps getting more fascinating.',
        caption: '',
        comments: [],
        createdAt: '2026-07-21T09:00:00Z',
        expiresAt: '2026-08-05T09:00:00Z',
      },
    ],
  };
}
